### ISSUE TITLE
[BUG] - Cannot deploy to vercel

### ISSUE THREAD

**Issue by Vette1123** [aliabb01/invoify#139]
#### Issue Summary

![image](https://github.com/aliabb01/invoify/assets/26345237/d0457b24-c1a8-43ef-ba21-88a06df0528a)

I cannot generate pdf on deployed next.js project on vercel, could you please provide more info about deploying to vercel?

#### Environment

- **Browser/Platform:** : chrome

#### Steps to Reproduce

Its working fine locally, but failing on deployed version only.

#### Expected Behavior

[What you expected to happen]

#### Actual Behavior

[What actually happened]

#### Screenshots/Logs

[If applicable, include relevant screenshots or error logs]

#### Additional Information

[Include any additional information that may help in diagnosing the issue]

#### Possible Solutions

[If you have suggestions for how to fix the issue, provide them here]

---

#### Acceptance Criteria

- [ ] The issue is confirmed and reproducible.
- [ ] Relevant details about the environment are provided.
- [ ] Steps to reproduce are clear and concise.
- [ ] Expected and actual behavior are described.
- [ ] Screenshots/logs (if applicable) are attached.
- [ ] Any additional relevant information is included.

---

[Note: Please replace the placeholders in square brackets with specific information related to your bug report.]

**Comment by aliabb01** [comment]
@Vette1123 Could you check the deployment logs in Vercel and see what it says?

**Comment by Vette1123** [comment]
@aliabb01 i just gave you a picture of the error above..

no such file or directory, open '/tmp/chromium-pack/fonts.tar.br'

**Comment by Thibaut738** [comment]
Hi, I also encountered the same problem. Is there a solution to this?

I only get this line in the deployment logs:
Chromium (1108766) downloaded to /vercel/path0/.cache/puppeteer/chrome/linux-1108766

**Comment by aliabb01** [comment]
@Vette1123 @Thibaut738. This issue most likely arises from this piece of code in [`generatePdfService.ts`](https://github.com/aliabb01/invoify/blob/master/services/invoice/server/generatePdfService.ts) file:

```ts
        // Launch the browser in production or development mode depending on the environment
        if (ENV === "production") {
            const puppeteer = await import("puppeteer-core");
            browser = await puppeteer.launch({
                args: chromium.args,
                defaultViewport: chromium.defaultViewport,
                executablePath: await chromium.executablePath(
                    CHROMIUM_EXECUTABLE_PATH
                ),
                headless:
                    chromium.headless === "new" ? true : chromium.headless,
            });
        } else if (ENV === "development") {
            const puppeteer = await import("puppeteer");
            browser = await puppeteer.launch({
                args: ["--no-sandbox", "--disable-setuid-sandbox"],
                headless: "new",
            });
        }
```

Not sure why this does not work in your deployments. I will try to clone the repo from GitHub and deploy that version to Vercel to see if it causes the same error.

**Comment by Vette1123** [comment]
@aliabb01 any updates?

**Comment by aliabb01** [comment]
> @aliabb01 any updates?

Tried cloning the app and then deployed it to Vercel as a separate project. Deployment was done through Vercel CLI by using `vercel deploy` command from the root of the cloned app. Everything seems to work. You can find the deployed test app [here](https://invoify-test.vercel.app).
