### ISSUE TITLE
[BUG] - Not a bug - Installation steps missed something

### ISSUE THREAD

**Issue by skeeperloyaltie** [aliabb01/invoify#245]
![image](https://github.com/aliabb01/invoify/assets/54027203/3b44122e-5cff-426f-bc1d-02d1523c5be8)

Just an error am getting on running
```npm run dev```

**Comment by aliabb01** [comment]
The command `next start` starts the app in production mode. 
But to make it work you have to build the application using `next build` command first.
Command `npm run dev` should work fine for development.

You can find more information about `next start` here: [Next.js docs](https://nextjs.org/docs/pages/api-reference/next-cli#production)

**Comment by skeeperloyaltie** [comment]
![image](https://github.com/aliabb01/invoify/assets/54027203/a4651f3b-b73c-4b2f-8dac-6a7d7aa1b7d9)
 still getting the above error

**Comment by aliabb01** [comment]
For npm build command to work, I believe you need to write `npm run build` instead of `npm build`
