### ISSUE TITLE
Not Generating Pdf

### ISSUE THREAD

**Issue by CubicDev1** [aliabb01/invoify#322]
when generating pdf then it showing this error
![image](https://github.com/aliabb01/invoify/assets/141395946/7a8cfbc2-6f5b-4861-ba74-993104c27676)

i have deploy in netliy and vercel but same error .
when i have tried in codespace then it is normal

**Comment by aliabb01** [comment]
It should be working now with this new commit 2e0ecd8

**Comment by CubicDev1** [comment]
ok it has been fixed
